channels:
- conda-forge

dependencies:
# Items required for basic level functionality
- gh-scoped-creds==4.1
- git==2.49.0
- jupyter-resource-usage==1.1.1
- jupyter_server==2.16.0
- jupyterhub==5.3.0
- jupyterlab==4.4.2
- jupyterlab-git==0.51.1
- jupytext==1.17.1
- nbgitpuller==1.2.2
- notebook==7.4.2
# DH-456
- otter-grader==6.1.3
- python==3.11.*

# Other items
- jupyter-server-proxy==4.4.0
- syncthing==1.29.2
- jupyter-rsession-proxy==2.2.1
- jupyter-syncthing-proxy==1.0.3
- traitlets==5.14.3
- appmode==1.0.0

# pip installed packages, conda is preferred
- pip==24.2
- pip:
  # for notebook exporting
  - nbconvert[webpdf]==7.16.6
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
  - jupyter-archive==3.4.0
  - rise==5.7.1
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - git-credential-helpers==0.2
  - jupyter-tree-download==1.0.1
